apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-java-demo
  labels:
    app: k8s-java-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-java-demo
  template:
    metadata:
      labels:
        app: k8s-java-demo
    spec:
      containers:
        - name: k8s-java-demo
          imagePullPolicy: Always
          image: weibh/k8s-java-demo
          env:
            - name: JAVA_OPTS
              value: -server -Xmx4000M -Xms4000M -Xmn600M -Xss256K
                -XX:+PrintFlagsFinal  -XX:+UnlockExperimentalVMOptions
                -Xlog:gc:/tmp/gc.log -Djava.security.egd=file:/dev/./urandom
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 5
            failureThreshold: 10
            timeoutSeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-java-demo
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: k8s-java-demo
  type: NodePort
